# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  repositories:
    - repository: template
      type: git
      name: Safe2Pay/yaml-templates
      ref: refs/heads/features/github-copy

pool:
  vmImage: 'windows-latest'

stages:
  - template: templates/stages/github-repository-sync.yml@template
    parameters:
      githubRepositoryName: 'PHP'